### ISSUE TITLE
GMP check is broken?

### ISSUE THREAD

**Issue by malex984** [Singular/LELA#3]
./configure --with-gmp="/opt/local"

results in 

checking for GMP >= 1.0... *******************************************************************************
 ERROR: GMP not found!
 GMP version 3.1.1 or greater with --enable-cxx is required for this library to compile. Please
 make sure GMP is installed and specify its location with the option
 --with-gmp=<prefix> when running configure.

whereas i have it all under that prefix:

/opt/local/include/gmp.h
/opt/local/include/gmpxx.h
/opt/local/lib/libgmp.10.dylib
/opt/local/lib/libgmp.3.dylib
/opt/local/lib/libgmp.a
/opt/local/lib/libgmp.dylib
/opt/local/lib/libgmp.la
/opt/local/lib/libgmpxx.4.dylib
/opt/local/lib/libgmpxx.a
/opt/local/lib/libgmpxx.dylib
/opt/local/lib/libgmpxx.la

the config.log contains 

g++ -o conftest    conftest.cpp  -L/opt/local/lib -lgmp -lgmpxx >&5
conftest.cpp:36:17: error: gmp.h: No such file or directory
...
and
g++ -o conftest    conftest.cpp  -L/opt/local/lib -lgmp -lgmpxx -L/opt/local/lib -lgmp -lgmpxx >&5
conftest.cpp:36:17: error: gmp.h: No such file or directory
...

So i guess you don't pass -I/opt/local/include to the checker!!!

AFAIK, we fixed this issue in libpolys so why not to use the fixed gmp check?

**Comment by hovinen** [comment]
The source of the problem is not immediately apparent to me. Could you send me your config.log? Thanks.

**Comment by malex984** [comment]
seems to work now
