### ISSUE TITLE
test-strassen-winograd

### ISSUE THREAD

**Issue by malex984** [Singular/LELA#4]
after your fix:

ERROR (at copy_impl in ../lela/blas/level3-generic.tcc:102): 
Precondition not met:A.rowdim () == B.rowdim ()
terminate called after throwing an instance of 'LELA::PreconditionFailed'
/bin/sh: line 5: 26878 Aborted                 ${dir}$tst
FAIL: test-strassen-winograd

**Comment by hovinen** [comment]
Should be fixed now. Thanks.
