### ISSUE TITLE
GaussJordan - another(!) use of undefined elements in testFaugereLachartre

### ISSUE THREAD

**Issue by malex984** [Singular/LELA#6]
lela/algorithms/gauss-jordan.tcc:271 :      ctx.F.mulin (d, aii); where d is undefined (but aii is ok)  

gdb backtrace:
#8  0x00000000004361c1 in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::GaussTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (this=0x7fffffffe1f0, A=..., L=..., d_0=..., P=..., r=@0x7fffffffb9c8, h=@0x7fffffffb9bc, d=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:271
#9  0x0000000000436607 in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::GaussTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (this=0x7fffffffe1f0, A=..., L=..., d_0=..., P=..., r=@0x7fffffffbf70, h=@0x7fffffffbf68, d=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:328
#10 0x000000000043690d in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::GaussTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (this=0x7fffffffe1f0, A=..., L=..., d_0=..., P=..., r=@0x7fffffffc520, h=@0x7fffffffc518, d=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:358
#11 0x000000000043690d in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::GaussTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (this=0x7fffffffe1f0, A=..., L=..., d_0=..., P=..., r=@0x7fffffffcad0, h=@0x7fffffffcac8, d=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:358
#12 0x000000000043690d in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::GaussTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (this=0x7fffffffe1f0, A=..., L=..., d_0=..., P=..., r=@0x7fffffffd088, h=@0x7fffffffd07c, d=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:358
#13 0x0000000000436607 in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::GaussTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (this=0x7fffffffe1f0, A=..., L=..., d_0=..., P=..., r=@0x7fffffffd630, h=@0x7fffffffd628, d=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:328
#14 0x000000000043690d in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::GaussTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (this=0x7fffffffe1f0, A=..., L=..., d_0=..., P=..., r=@0x7fffffffda78, h=@0x7fffffffd78c, d=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:358
#15 0x000000000042fbbe in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::echelonizeLELA::DenseMatrix<Number, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (

```
this=0x7fffffffe1f0, A=..., P=..., rank=@0x7fffffffda78, det=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:421
```
#16 0x000000000042971e in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::echelonizeLELA::DenseMatrix<Number > (this=0x7fffffffe1f0, A=..., P=..., rank=@0x7fffffffda78, det=...)

```
at ../lela/algorithms/gauss-jordan.h:124
```
#17 0x0000000000420e64 in LELA::EchelonForm<MyModular<float>, LELA::AllModules<MyModular<float> > >::echelonize (this=0x7fffffffe1d8, A=..., reduced=false,

```
method=LELA::EchelonForm<MyModular<float>, LELA::AllModules<MyModular<float> > >::METHOD_ASYMPTOTICALLY_FAST_GJ) at ../lela/solutions/echelon-form.h:130
```
#18 0x000000000041a36d in LELA::FaugereLachartre<MyModular<float>, LELA::AllModules<MyModular<float> > >::echelonize<LELA::SparseMatrix<Number, LELA::SparseVector<Number, std::vector<unsigned int>, std::vector<Number, std::allocator<Number> > >, LELA::VectorRepresentationTypes::Sparse> > (this=0x7fffffffe1d0, R=..., X=..., rank=@0x7fffffffe378, det=...) at ../lela/algorithms/faugere-lachartre.tcc:297
#19 0x00000000004158d3 in testFaugereLachartre<MyModular<float> > (R=..., text=0x55552c "GF(5)", m=96, n=128) at test-faugere-lachartre.C:179
#20 0x000000000040edec in main (argc=1, argv=0x7fffffffe548) at test-faugere-lachartre.C:241

**Comment by malex984** [comment]
same happens in test-gauss-jordan

#8  0x0000000000419ae1 in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::GaussTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (this=0x7fffffffe220, A=..., L=..., d_0=..., P=..., r=@0x7fffffffc1b8, h=@0x7fffffffc1ac, d=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:271
#9  0x0000000000419f27 in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::GaussTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (this=0x7fffffffe220, A=..., L=..., d_0=..., P=..., r=@0x7fffffffc768, h=@0x7fffffffc75c, d=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:328
#10 0x0000000000419f27 in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::GaussTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (this=0x7fffffffe220, A=..., L=..., d_0=..., P=..., r=@0x7fffffffcd18, h=@0x7fffffffcd0c, d=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:328
#11 0x0000000000419f27 in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::GaussTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (this=0x7fffffffe220, A=..., L=..., d_0=..., P=..., r=@0x7fffffffd2c8, h=@0x7fffffffd2bc, d=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:328
#12 0x0000000000419f27 in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::GaussTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (this=0x7fffffffe220, A=..., L=..., d_0=..., P=..., r=@0x7fffffffd878, h=@0x7fffffffd86c, d=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:328
#13 0x0000000000419f27 in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::GaussTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (this=0x7fffffffe220, A=..., L=..., d_0=..., P=..., r=@0x7fffffffde28, h=@0x7fffffffde1c, d=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:328
#14 0x0000000000419f27 in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::GaussTransformLELA::DenseMatrix<Number, LELA::DenseMatrix<Number>, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (this=0x7fffffffe220, A=..., L=..., d_0=..., P=..., r=@0x7fffffffe218, h=@0x7fffffffdf7c, d=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:328
#15 0x0000000000417456 in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::echelonizeLELA::DenseMatrix<Number, LELA::DensePivotStrategy<MyModular<float>, LELA::AllModules<MyModular<float> > > > (
    this=0x7fffffffe220, A=..., P=..., rank=@0x7fffffffe218, det=..., PS=...) at ../lela/algorithms/gauss-jordan.tcc:421
#16 0x0000000000415bc2 in LELA::GaussJordan<MyModular<float>, LELA::AllModules<MyModular<float> > >::echelonizeLELA::DenseMatrix<Number > (this=0x7fffffffe220, A=..., P=..., rank=@0x7fffffffe218, det=...)
    at ../lela/algorithms/gauss-jordan.h:124
#17 0x0000000000413707 in testGaussTransform<MyModular<float> > (F=..., m=96, n=96) at test-gauss-jordan.C:55
#18 0x000000000040ef1c in main (argc=1, argv=0x7fffffffe558) at test-gauss-jordan.C:216

**Comment by hovinen** [comment]
This seems actually to be the same issue as the other one. It should be fixed now.

**Comment by malex984** [comment]
same here, but in lela/algorithms/gauss-jordan.tcc:328

326         Element d_1;
327 
328         GaussTransform (A_1, L, d_0, P, r_1, h_1, d_1, PS);

d_1 is undefined!

**Comment by hovinen** [comment]
Sorry, missed those ;-) Fixed now.
